version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_todoapp
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ChangeMeStrong!}
      MYSQL_DATABASE: todoapp_db
      MYSQL_USER: todoapp_user
      MYSQL_PASSWORD: ${MYSQL_TODOAPP_PASSWORD:-TodoAppPass123!}
      TZ: UTC
    ports:
      - "3306:3306"
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-authentication-plugin=mysql_native_password',
      '--max_allowed_packet=256M',
      '--innodb_buffer_pool_size=256M',
      '--innodb_log_file_size=64M',
      '--general_log=1',
      '--general_log_file=/var/log/mysql/general.log'
    ]
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
      - ./mysql/logs:/var/log/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql_workbench
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    ports:
      - "8080:3000"
    volumes:
      - workbench_config:/config
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 15s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
  workbench_config: 